### ISSUE TITLE
CP doesn't seach for torrents

### ISSUE THREAD

**Issue by Mahmoud87** [linuxserver/docker-couchpotato#17]
Hello guys, CP doesn't search for torrents, recently I added movies but CP doesn't snatch them from the trackers even with different qualities. It stopped all of a sudden finding data even though the movies exist on the trackers.

I am running the docker on Rockstor

This is the logs from CP when I search for Snowden movie.

```
12-02 21:45:24 ERROR [   couchpotato.core.event] Error in event "automation.get_chart_list", that wasn't caught: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/app/couchpotato/couchpotato/core/media/movie/providers/automation/base.py", line 44, in _getChartList
    return self.getChartList()
  File "/app/couchpotato/couchpotato/core/media/movie/providers/automation/bluray.py", line 129, in getChartList
    movie = self.search(name, year)
  File "/app/couchpotato/couchpotato/core/media/movie/providers/automation/base.py", line 48, in search
    cache_name = name.decode('utf-8').encode('ascii', 'ignore')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\x92' in position 17: ordinal not in range(128)
encoding=UTF-8 debug=False args=['--config_file=/config/config.ini', '--data_dir=/config/data'] app_dir=/app/couchpotato data_dir=/config/data desktop=None options=Namespace(config_file='/config/config.ini', console_log=False, daemon=False, data_dir='/config/data', debug=False, pid_file='/config/data/couchpotato.pid', quiet=False)  
12-02 21:47:10 INFO [core.media.movie.searcher] Search for Snowden in 1080p ignoring ETA 
12-02 21:47:10 INFO [hpotato.core.plugins.base] Opening url: get https://www.torrentbytes.net/browse.php?search=snowden+2016&cat=5, data: [] 
12-02 21:47:10 INFO [hpotato.core.plugins.base] Opening url: get https://alpharatio.cc/torrents.php?action=advanced&searchstr=Snowden+2016&scene=&filter_cat[7]=1, data: [] 
12-02 21:47:10 INFO [hpotato.core.plugins.base] Opening url: get https://www.torrentleech.org/torrents/browse/index/query/snowden/categories/13, data: [] 
12-02 21:47:10 INFO [hpotato.core.plugins.base] Opening url: get https://iptorrents.eu/t?48=&q=%22snowden%22+2016&qf=ti#torrents&p=1, data: [] 
12-02 21:47:13 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/tt3774114?api_key=xxx&append_to_response=alternative_titles&language=en, data: [] 
12-02 21:47:13 INFO [ie.providers.info.omdbapi] Found: Snowden (2016) 
12-02 21:47:15 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/302401?api_key=xxx&append_to_response=alternative_titles&language=en, data: [] 
12-02 21:47:15 INFO [core.media.movie.searcher] Search for Snowden in 1080p ignoring ETA 
12-02 21:47:15 INFO [hpotato.core.plugins.base] Opening url: get https://www.torrentbytes.net/browse.php?search=snowden+2016&cat=5, data: [] 
12-02 21:47:15 INFO [ie.providers.info.omdbapi] Found: Snowden (2016) 
12-02 21:47:15 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/tt3774114?api_key=xxx&append_to_response=alternative_titles&language=en, data: [] 
12-02 21:47:16 INFO [core.media.movie.searcher] Search for Snowden in 1080p ignoring ETA 
12-02 21:47:16 INFO [hpotato.core.plugins.base] Opening url: get https://www.torrentbytes.net/browse.php?search=snowden+2016&cat=5, data: [] 
```
```

**Comment by sparklyballs** [comment]
This appears to be a couchpotato issue.

https://couchpota.to/forum/viewtopic.php?f=3&t=50074

**Comment by Mahmoud87** [comment]
I guess we'll have to wait for an update for CP then, cheers :)
