### ISSUE TITLE
Renaming file - Post processing Failed

### ISSUE THREAD

**Issue by mrvaghani** [linuxserver/docker-couchpotato#24]
I am running Docker on Ubuntu 16.04 server

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

```

My docker create command:

```
docker create \
	--name=couchpotato \
	-v /apps/couchpotato/config:/config \
	-v /nfs:/downloads \
	-v /nfs/movies:/movies \
	-e PGID=1000 -e PUID=1000  \
	-e TZ=EDT \
	-p 5050:5050 \
	--restart unless-stopped \
	linuxserver/couchpotato
```

Docker Logs:

```
vaghanim@usenet-docker:/$ docker logs couchpotato
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-install: executing...
Cloning into '/app/couchpotato'...
[cont-init.d] 30-install: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address in use
vaghanim@usenet-docker:/$

```

I have NFS share mounted on the following three directories:

```
/nfs/movies
/nfs/torrents
/nfs/tv
```

I have Couchpotato set to look for files in 
`/downloads/mydownloads/completed/movies/`

And I am having it move the processed copy to:
`/movies/`

Problem:
When I have the following folder structure:

```
- /downloads/mydownloads/completed/movies/myfavmovie01
- /downloads/mydownloads/completed/movies/myfavmovie02
- /downloads/mydownloads/completed/movies/myfavmovie03
```
Couchpotato is not able to look inside `/downloads/mydownloads/completed/movies/` and start processing the folders. However, if I manually ask Couchpotato to scan `/downloads/mydownloads/completed/movies/myfavmovie01/` then it will find the `myfavmovie.mkv` and process it successfully.

Everytime I force it to scan the `/downloads/mydownloads/completed/movies/` level structure, I get the following errors in the couchpotato logs:

```
07-19 03:12:29 ERROR
[tato.core.plugins.browser] Failed getting directory "/root" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 96, in view dirs = self.getDirectories(path = path, show_hidden = show_hidden) File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 60, in getDirectories for f in os.listdir(path): OSError: [Errno 13] Permission denied: '/root'
07-19 03:42:52 ERROR
[tato.core.plugins.browser] Failed getting directory "/root" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 96, in view dirs = self.getDirectories(path = path, show_hidden = show_hidden) File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 60, in getDirectories for f in os.listdir(path): OSError: [Errno 13] Permission denied: '/root'
07-19 03:43:07 ERROR
[tato.core.plugins.browser] Failed getting directory "/root" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 96, in view dirs = self.getDirectories(path = path, show_hidden = show_hidden) File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 60, in getDirectories for f in os.listdir(path): OSError: [Errno 13] Permission denied: '/root'
07-19 03:43:41 ERROR
[tato.core.plugins.browser] Failed getting directory "/root" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 96, in view dirs = self.getDirectories(path = path, show_hidden = show_hidden) File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 60, in getDirectories for f in os.listdir(path): OSError: [Errno 13] Permission denied: '/root'
07-19 03:43:42 ERROR
[tato.core.plugins.browser] Failed getting directory "/root/" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 96, in view dirs = self.getDirectories(path = path, show_hidden = show_hidden) File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 60, in getDirectories for f in os.listdir(path): OSError: [Errno 13] Permission denied: '/root'
```

Please let me know if you need any more information from me.

Thank you for providing this docker image, it is extremely helpful and I appreciate any help you can provide.

**Comment by j0nnymoe** [comment]
Hi, not sure if this is still an issue or not but I suspect that it's related to the Permissions and/or NFS mount's that's causing the issue here.

**Comment by thelamer** [comment]
'''socket.error: [Errno 98] Address in use'''

use a different port that one is in use.
