### ISSUE TITLE
Unable to restart service gracefully from UI

### ISSUE THREAD

**Issue by mist0706** [linuxserver/docker-couchpotato#28]
Once up, running and configured the docker works great except for the inability to restart the daemon from the couchpotato interface. To restart the daemon one must restart the entire container

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 16.04.3

```11-07 20:35:29 INFO [chpotato.core._base._core] Restarting
11-07 20:35:29 INFO Shutting down thread pool
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: _core
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: _core
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: clientscript
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: clientscript
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: desktop
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: desktop
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: downloader
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: downloader
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: scheduler
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: scheduler
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: updater
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: automation
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: browser
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded core: updater
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: category
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: automation
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: custom
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: browser
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: dashboard
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: category
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: custom
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling file.cleanup, interval: hours = 24, minutes = 0, seconds = 0
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: dashboard
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: file
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling file.cleanup, interval: hours = 24, minutes = 0, seconds = 0
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: log
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: file
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: manage
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: log
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: profile
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: manage
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: profile
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: quality
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: quality
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling movie.clean_releases, interval: hours = 12, minutes = 0, seconds = 0
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: release
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling movie.clean_releases, interval: hours = 12, minutes = 0, seconds = 0
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: release
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: renamer
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: renamer
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: scanner
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: score
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: subtitle
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: trailer
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: userscript
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: wizard
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: scanner
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: blackhole
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: score
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: subtitle
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: deluge
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: trailer
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: userscript
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: hadouken
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded plugin: wizard
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: blackhole
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: nzbget
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: nzbvortex
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: pneumatic
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: deluge
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: hadouken
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: putio
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: qbittorrent_
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: nzbget
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: nzbvortex
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: pneumatic
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: putio
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: qbittorrent_
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: rtorrent_
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: sabnzbd
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: synology
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: transmission
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: rtorrent_
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: utorrent
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: sabnzbd
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: androidpn
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: boxcar2
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: synology
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling core.check_messages, interval: hours = 12, minutes = 0, seconds = 0
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: transmission
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling core.clean_messages, interval: hours = 0, minutes = 0, seconds = 15
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: core
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded downloaders: utorrent
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: discord
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: androidpn
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: boxcar2
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling core.check_messages, interval: hours = 12, minutes = 0, seconds = 0
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling core.clean_messages, interval: hours = 0, minutes = 0, seconds = 15
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: core
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: email_
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: discord
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: emby
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: email_
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: emby
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: growl
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: homey
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: join
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: nmj
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: growl
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: homey
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: join
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: nmj
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: notifymyandroid
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: plex
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: prowl
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: pushalot
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: notifymyandroid
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: pushbullet
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: pushover
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: plex
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: script
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: prowl
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: slack
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: pushalot
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: synoindex
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: pushbullet
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: telegrambot
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: pushover
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: toasty
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: script
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: slack
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: synoindex
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: telegrambot
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: trakt
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: toasty
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: trakt
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: twitter
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: webhook
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: xbmc
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: twitter
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: webhook
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: xbmc
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: xmpp_
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media__base_library: library
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded notifications: xmpp_
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media__base_library: library
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media__base_matcher: matcher
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media__base_media: media
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media__base_matcher: matcher
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media__base_media: media
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media__base_search: search
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media__base_search: search
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media__base: searcher
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media__base: searcher
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie__base: _base
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie__base: _base
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie: charts
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie: charts
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie: library
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie: library
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: bluray
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: bluray
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: crowdai
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: crowdai
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: flixster
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: flixster
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: goodfilms
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: goodfilms
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: hummingbird
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: hummingbird
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: imdb
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: imdb
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: itunes
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: itunes
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: letterboxd
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: letterboxd
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: popularmovies
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation: popularmovies
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling updater.check, interval: hours = 24, minutes = 0, seconds = 0
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling updater.check, interval: hours = 24, minutes = 0, seconds = 0
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation_trakt: trakt
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_automation_trakt: trakt
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_info: _modifier
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_info: _modifier
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_info: couchpotatoapi
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_info: couchpotatoapi
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_info: fanarttv
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_info: fanarttv
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_info: omdbapi
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_info: omdbapi
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_info: themoviedb
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_info: themoviedb
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_metadata: mediabrowser
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_metadata: mediabrowser
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_metadata: ps3
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_metadata: ps3
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_metadata: wdtv
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_metadata: wdtv
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_metadata: wmc
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_metadata: wmc
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_metadata: xbmc
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_metadata: xbmc
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_nzb: binsearch
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_nzb: newznab
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_nzb: binsearch
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_nzb: nzbclub
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_nzb: newznab
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_nzb: omgwtfnzbs
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_nzb: nzbclub
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: alpharatio
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_nzb: omgwtfnzbs
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: awesomehd
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: alpharatio
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: bithdtv
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: awesomehd
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: bitsoup
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: bithdtv
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: hd4free
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: bitsoup
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: hdbits
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: hd4free
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: ilovetorrents
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: hdbits
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: iptorrents
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: ilovetorrents
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: kickasstorrents
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: iptorrents
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: magnetdl
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: kickasstorrents
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: morethantv
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: magnetdl
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: morethantv
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: passthepopcorn
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: rarbg
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: passthepopcorn
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: sceneaccess
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: rarbg
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: scenetime
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: sceneaccess
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: thepiratebay
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: scenetime
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentbytes
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: thepiratebay
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentday
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentbytes
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentleech
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentday
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentpotato
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentleech
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentshack
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentpotato
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentz
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentshack
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: yts
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: torrentz
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_torrent: yts
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_trailer: hdtrailers
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: allocine
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_trailer: hdtrailers
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: appletrailers
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: criticker
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: allocine
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: filmcentrum
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: appletrailers
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: filmstarts
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: criticker
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: filmweb
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: filmcentrum
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: flickchart
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: filmstarts
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: imdb
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: filmweb
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: letterboxd
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: flickchart
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: moviemeter
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: imdb
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: moviesio
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: letterboxd
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: reddit
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: moviemeter
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: rottentomatoes
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: moviesio
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: tmdb
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: reddit
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: trakt
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: rottentomatoes
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: youteather
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: tmdb
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: trakt
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie: searcher
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie_providers_userscript: youteather
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie: suggestion
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie: searcher
11-07 20:35:32 INFO [  couchpotato.core.loader] Loaded media_movie: suggestion
11-07 20:35:32 INFO [       couchpotato.runner] Starting server on port 5050
11-07 20:35:32 INFO [       couchpotato.runner] Starting server on port 5050
11-07 20:35:32 INFO [chpotato.core._base._core] Launching browser
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling renamer.check_snatched, interval: hours = 0, minutes = 1, seconds = 0
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling renamer.check_snatched_forced, interval: hours = 2, minutes = 0, seconds = 0
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling updater.check, interval: hours = 24, minutes = 0, seconds = 0
11-07 20:35:32 INFO [chpotato.core._base._core] Launching browser
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling "movie.searcher.all", cron: day = *, hour = 9, minute = 55
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling automation.add_movies, interval: hours = 12, minutes = 0, seconds = 0
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling "movie.searcher.all", cron: day = *, hour = 9, minute = 55
11-07 20:35:32 INFO [otato.core.plugins.manage] Updating manage library: /movies
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling updater.check, interval: hours = 24, minutes = 0, seconds = 0
11-07 20:35:32 ERROR [       couchpotato.runner] Failed starting: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use

11-07 20:35:32 INFO [otato.core.plugins.manage] Updating manage library: /movies
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling renamer.check_snatched, interval: hours = 0, minutes = 1, seconds = 0
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling automation.add_movies, interval: hours = 12, minutes = 0, seconds = 0
11-07 20:35:32 CRITICAL [                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use

Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
11-07 20:35:32 INFO [tato.core._base.scheduler] Scheduling renamer.check_snatched_forced, interval: hours = 2, minutes = 0, seconds = 0
```

**Comment by sparklyballs** [comment]
i'm not seeing the problem

basically don't restart the app via the webui
