### ISSUE TITLE
Couchpotato not working anymore

### ISSUE THREAD

**Issue by yoyos** [linuxserver/docker-couchpotato#35]
Couchpotato isn't working anymore, have this error. You have an idea ? :)

Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 142, in runCouchPotato
    db.open()
  File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
    res = super(SuperThreadSafeDatabase, self).open(*args, **kwargs)
  File "/app/couchpotato/libs/CodernityDB/database.py", line 571, in open
    index.open_index()
  File "/app/couchpotato/libs/CodernityDB/tree_index.py", line 160, in open_index
    self.root_flag = struct.unpack('<c', self.buckets.read(1))[0]
struct.error: unpack requires a string argument of length 1

**Comment by j0nnymoe** [comment]
Host OS? / docker command? / docker logs? / have you pulled the latest image and rebuilt the container with that?

**Comment by yoyos** [comment]
Debian
/
docker-compose with

> version: '2'
services:
  web:
    build: .
    ports:
      - 5050:5050
    working_dir: /home
    volumes:
      - /data/entertainment/coughpotato/config:/config
      - /data/entertainment/media/Torrents:/downloads
      - /data/entertainment/media/Movies:/movies
    environment:
      TERM: xterm
      PGID: 33
      PUID: 33
      TZ: Europe/Brussels
    restart: always
    container_name: couchpotato
networks:
  default:
    external:
      name: my_network
/
docker logs -f couchpotato gives me spam of 

> Traceback (most recent call last):
File "/app/couchpotato/CouchPotato.py", line 135, in 
l.run()
File "/app/couchpotato/CouchPotato.py", line 89, in run
runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
File "/app/couchpotato/couchpotato/runner.py", line 142, in runCouchPotato
db.open()
File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
res = f(*args, **kwargs)
File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
res = super(SuperThreadSafeDatabase, self).open(*args, **kwargs)
File "/app/couchpotato/libs/CodernityDB/database.py", line 571, in open
index.open_index()
File "/app/couchpotato/libs/CodernityDB/tree_index.py", line 160, in open_index
self.root_flag = struct.unpack('<c', self.buckets.read(1))[0]
struct.error: unpack requires a string argument of length 1
/
yes I have pulled the latest image and rebuilt the container with that

**Comment by j0nnymoe** [comment]
I assume this has worked for you before?

**Comment by yoyos** [comment]
Yes, for years :D

**Comment by j0nnymoe** [comment]
I would report that issue to couch directly, they should be able to point to why that error is happening.
If it is an issue with the container, report back and reopen this ticket with what they say :)

**Comment by yoyos** [comment]
There is not issue tab on https://github.com/CouchPotato/CouchPotatoServer

Do you have an idea where I should ask this please ? ;)

**Comment by j0nnymoe** [comment]
Their forum is probably the best bet.

**Comment by aptalca** [comment]
Also, don't build it, pull the image from docker hub. I don't know what you're building from
